CREATE TABLE players (
    player_id INT PRIMARY KEY,
    short_name TEXT,
    long_name TEXT,
    dob DATE,
    age INT,
    height_cm INT,
    weight_kg INT,
    player_positions TEXT,
    overall INT,
    potential INT,
    preferred_foot TEXT,
    weak_foot INT,
    skill_moves INT,
    international_reputation INT,
    club_team_id INT,
    nationality_id INT
); 

CREATE TABLE clubs (
    club_team_id INT PRIMARY KEY,
    club_name TEXT,
    league_id INT,
    league_name TEXT,
    league_level INT,
    club_position TEXT,
    club_jersey_number INT,
    club_joined_date DATE,
    club_contract_valid_until_year INT
);

CREATE TABLE nationalities (
    nationality_id INT PRIMARY KEY,
    nationality_name TEXT,
    nation_team_id INT,
    nation_position TEXT,
    nation_jersey_number INT
);

CREATE TABLE skills (
    player_id INT PRIMARY KEY,
    pace INT,
    shooting INT,
    passing INT,
    dribbling INT,
    defending INT,
    physic INT,
    attacking_crossing INT,
    attacking_finishing INT,
    attacking_heading_accuracy INT,
    attacking_short_passing INT,
    attacking_volleys INT,
    skill_dribbling INT,
    skill_curve INT,
    skill_fk_accuracy INT,
    skill_long_passing INT,
    skill_ball_control INT,
    movement_acceleration INT,
    movement_sprint_speed INT,
    movement_agility INT,
    movement_reactions INT,
    movement_balance INT,
    power_shot_power INT,
    power_jumping INT,
    power_stamina INT,
    power_strength INT,
    power_long_shots INT,
    mentality_aggression INT,
    mentality_interceptions INT,
    mentality_positioning INT,
    mentality_vision INT,
    mentality_penalties INT,
    mentality_composure INT,
    defending_marking_awareness INT,
    defending_standing_tackle INT,
    defending_sliding_tackle INT,
    goalkeeping_diving INT,
    goalkeeping_handling INT,
    goalkeeping_kicking INT,
    goalkeeping_positioning INT,
    goalkeeping_reflexes INT,
    goalkeeping_speed INT,
    ls INT,
    st INT,
    rs INT,
    lw INT,
    lf INT,
    cf INT,
    rf INT,
    rw INT,
    lam INT,
    cam INT,
    ram INT,
    lm INT,
    lcm INT,
    cm INT,
    rcm INT,
    rm INT,
    lwb INT,
    ldm INT,
    cdm INT,
    rdm INT,
    rwb INT,
    lb INT,
    lcb INT,
    cb INT,
    rcb INT,
    rb INT,
    gk INT
);
